# versinons need updating
name: semifield-reports
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - hydra-core
  - hydra_colorlog
  - reportlab
  - fpdf
  - pip:
      - omegaconf
      - PyYAML
      - pytest
      - azure-storage-blob
      - azure-core
      - tqdm
      - shyaml