# versinons need updating
name: semifdr
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3 
  - python=3.10
  - pip:
      - azure-core==1.29.7
      - azure-storage-blob==12.19.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0