# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - date_ranges: date_ranges
  - hydra: default
  - paths: default

report:
task: ???
#folders and their corresponding ile types that will be matched in the data directory
matching_folders: {'images':'jpg','instance_masks':'png','semantic_masks':'png','metadata':'json'}