# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - date_ranges: date_ranges
  - hydra: default
  - paths: default

report:
task: ???
#folders that will be matched in the data directory
matching_folders: ['images','instance_masks','semantic_masks','metadata']