# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_  
  - paths: default

report:
pipeline:
- list_blob_contents
  # - export_blob_metrics
  # - local_batch_table_generator

#folders and their corresponding ile types that will be matched in the data directory
matching_folders: {'images':'jpg','instance_masks':'png','semantic_masks':'png','metadata':'json'}

list_blob_contents:
  unprocessed_folders: 
    - images
    - autosfm
    - metadata
    - meta_masks
  processed_folders: 
    - autosfm
    - metadata
    - meta_masks
  file_extensions:
    images: ['.jpg']
    raw_images: ['.arw', '.raw']
    metadata: ['.json']
    meta_masks/semantic_masks: ['.png']
    
  batch_prefixes:
    - MD
    - TX
    - NC
